### ISSUE TITLE
Tag current version

### ISSUE THREAD

**Issue by rosik** [pygy/LuLPeg#14]
Hi. I've imported your rockspec in [tarantool rocks](https://github.com/tarantool/rocks) as `scm-1` version.
I would also like to release something like `0.1.0-1.rockspec`, but there is no tags in your repo.
Could you please tag the latest version to be referenced as 0.1

**Comment by pygy** [comment]
Hi, thanks for adding the lib to your vetted collection!

Is [this](https://github.com/pygy/LuLPeg/tree/v0.1) ok for you?

**Comment by rosik** [comment]
Yeah, great, thank you
