### ISSUE TITLE
Self-contained version?

### ISSUE THREAD

**Issue by LoganDark** [pygy/LuLPeg#18]
For example, for inclusion in a sandboxed environment where `require` doesn't exist.

**Comment by pygy** [comment]
Hi @LoganDark!

You can take https://github.com/pygy/LuLPeg/blob/master/lulpeg.lua and replace the last non-comment line (`return require"init"`) with `LuLPeg = require"init"`. That will create a global with bound to the lib.

`require` in that file is actually a local shim, it works even if your global env doesn't have it.

You may have to tweak `re.lua` in a similar fashion if you also want to use it.

**Comment by LoganDark** [comment]
Sorry, I've already tested this.

`lulpeg.lua` is self-contained - it doesn't actually require anything if you add cases for `math`, `string`, and `table` to the `require` function. Anyway, I've figured out that this is in no way regex and it's instead a very weird and complicated pattern thing instead(?)

In any case, thanks for the help.
