### ISSUE TITLE
Lua 5.3 Compability

### ISSUE THREAD

**Issue by jacobdufault** [pygy/LuLPeg#3]
There are a few issues when running under Lua 5.3, ie, `loadstring` has become `load`, and there are a few other issues (ie, running the tests for [typedlua](https://github.com/andremm/typedlua) fails in 5.3 but succeeds in 5.2). I have a version of typedlua [here](https://github.com/jacobdufault/typedlua) that will automatically use LuLPeg instead of lpeg.

I tried running the tests to give you a more concrete error report but I'm not sure how to execute some of them.

**Comment by pygy** [comment]
Could you give it a try?

On my end, it works properly with both my tests and typed Lua.

The fix was trivial but I forgot to commit it back in January...

**Comment by pygy** [comment]
@jacobdufault bibidi-bump?

**Comment by jacobdufault** [comment]
Sorry, I don't this setup anymore. I'll close the issue.
