### ISSUE TITLE
Some tests fails with lulpeg ? 

### ISSUE THREAD

**Issue by tst2005** [pygy/LuLPeg#7]
Hello it's me again,

I see you have your own way to pack lulpeg.lua.
I tried to pack the lulpeg components (`src/*.lua`) with my own [lua-aio][lua-aio] util.
To compare our [lulpeg.lua][lulpeg.lua] result to my [lulpeg-aio.lua][lulpeg-aio.lua] I tried to run the lpeg-0.12 tests suite.

I got the both result, that is good...
... but some tests fails.
Unfortunately I can not compare LuLPeg to LPeg because I have a LPeg v0.10 that completely fails the 0.12 tests.

- Is LuLPeg does not pass all lpeg 0.12 tests ?
- Is it known ?
- Do you get the same result ?
```
lulpeg/tests$ for lua in luajit lua5.1 lua5.2; do for lulpeg in lulpeg lulpeg-aio; do echo "testing $lulpeg with $lua"; $lua lpeg.0.12.test.lua $lulpeg |tail -1; done; done               
testing lulpeg with luajit
OK      Success:        6093    Failures:       70
testing lulpeg-aio with luajit
OK      Success:        6093    Failures:       70
testing lulpeg with lua5.1
OK      Success:        6093    Failures:       70
testing lulpeg-aio with lua5.1
OK      Success:        6093    Failures:       70
testing lulpeg with lua5.2
OK      Success:        6092    Failures:       71
testing lulpeg-aio with lua5.2
OK      Success:        6092    Failures:       71
```

[lulpeg.lua]: https://github.com/pygy/LuLPeg/blob/master/lulpeg.lua
[lulpeg-aio.lua]: https://github.com/tst2005/lulpeg/blob/all-in-one/lulpeg-aio.lua

**Comment by pygy** [comment]
Yes, it is expected. Most of these tests are about grammar validation (LuLPeg accepts invalid grammars that do infinite recursion), some are related to tail call elimination in proper finite automaton (LPeg does it, LuLPeg doesn't), and IIRC some are related to GC not occurring at the same moment in LPeg and LuLPeg.

Actually, you can see the error categories in the `tests/lpeg.0.12.test.lua` output:

>Error Messages
Tail call elimination and stack size
haveloop and badgrammar
Garbage collection
re error messages

As long as the error count stays at 70/71 and errors occur between tags, LuLPeg should be considered OK. These issues are documented in the README.

Good to know it's working with lua-aio :-).

**Comment by tst2005** [comment]
Thanks for you answer.

> These issues are documented in the README.

Oh ok... I should really read it :-D
