### ISSUE TITLE
Add to luarocks

### ISSUE THREAD

**Issue by leafo** [pygy/LuLPeg#9]
I notice this isn't in luarocks, any reason why not?

**Comment by pygy** [comment]
None in particular, I had yet to get acquainted with the rocks tooling / rockspec thing when I wrote LuLPeg.

**Comment by saucisson** [comment]
It seems that you have a rockspec, but did not upload it to luarocks. Can you please do the upload?

**Comment by pygy** [comment]
Done! Sorry for the delay.
